# Generated by Django 4.1.4 on 2023-01-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movie/static/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Person_name', models.CharField(max_length=250)),
                ('Person_lastname', models.CharField(max_length=250)),
                ('Person_email', models.EmailField(blank=True, max_length=100)),
                ('Person_image', models.ImageField(upload_to='movie/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Uyelik',
            fields=[
                ('Uyelik_turu', models.IntegerField(primary_key=True, serialize=False)),
                ('Uyelik_date', models.DateField()),
                ('Uyelik_name', models.CharField(max_length=250)),
                ('Uyelik_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('Trainer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Trainer_name', models.CharField(max_length=100)),
                ('Trainer_lastname', models.CharField(max_length=350)),
                ('Trainer_img', models.ImageField(upload_to='movie/static/images')),
                ('Trainer_desc', models.CharField(max_length=160)),
                ('Trainer_fb', models.URLField(blank=True, null=True)),
                ('Trainer_tw', models.URLField(blank=True, null=True)),
                ('Trainer_ln', models.URLField(blank=True, null=True)),
                ('Trainer_type', models.CharField(max_length=20)),
                ('Person_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('Program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Program_title', models.CharField(max_length=100)),
                ('Program_description', models.CharField(max_length=50)),
                ('Trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Uyelik_turu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.uyelik'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Class_name', models.CharField(max_length=50)),
                ('Class_desc', models.CharField(max_length=500)),
                ('Class_dayOfTheWeek', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('Class_finishingtime', models.TimeField(verbose_name='Time')),
                ('Class_beginningtime', models.TimeField(verbose_name='Time')),
                ('Class_img', models.ImageField(upload_to='movie/static/images')),
                ('Program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.program')),
                ('Trainer_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.trainer')),
            ],
        ),
    ]
