# Generated by Django 4.1.3 on 2022-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyelik',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
