# Generated by Django 4.1.3 on 2022-11-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_uyelik_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Person_name', models.CharField(max_length=250)),
                ('Person_lastname', models.CharField(max_length=250)),
                ('Person_email', models.EmailField(blank=True, max_length=100)),
                ('Person_image', models.ImageField(upload_to='movie/static/images/')),
            ],
        ),
        migrations.RenameField(
            model_name='program',
            old_name='description',
            new_name='Program_description',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='title',
            new_name='Program_title',
        ),
        migrations.RenameField(
            model_name='uyelik',
            old_name='url',
            new_name='Uyelik_url',
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uyelik',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uyelik',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uyelik',
            name='title',
        ),
        migrations.AddField(
            model_name='program',
            name='Program_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyelik',
            name='Uyelik_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyelik',
            name='Uyelik_turu',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('Trainer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Trainer_name', models.CharField(max_length=100)),
                ('Trainer_lastname', models.CharField(max_length=350)),
                ('Trainer_img', models.ImageField(upload_to='movie/static/images')),
                ('Trainer_email', models.EmailField(blank=True, max_length=70)),
                ('Person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Uyelik_turu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.uyelik'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Class_date', models.DateField(auto_now_add=True)),
                ('Class_time', models.TimeField(verbose_name='Time')),
                ('Program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='Trainer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.trainer'),
            preserve_default=False,
        ),
    ]
