# Generated by Django 4.1.3 on 2022-11-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.class')),
                ('Trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.trainer')),
            ],
        ),
    ]
